### ISSUE TITLE
CXToken: Authentication Failed

### ISSUE THREAD

**Issue by melmols** [checkmarx-ts/checkmarx-github-action#2]
Hi,

Is token based authentication available for Github actions? I couldn't find it in the source code and its failing. (Tested successfully locally)

**Comment by miguelfreitas93** [comment]
does it was solved ?

**Comment by miguelfreitas93** [comment]
if you provide cxToken, please do not use credentials

**Comment by melmols** [comment]
Hi,

Following a login authentication error, the token was tested locally and within circle ci and seemed to work fine. However I have en countered in the past that with existing projects, ProjectName and cxTeam name must be exactly the same. I've noticed this: 

**Project name will be always the name of the Repository concatenated with branch scanned. For example: "TestRepository-master**"

Would it be plausible that this might be the issue with existing projects? I'm running out of options...

**Comment by miguelfreitas93** [comment]
@melmols what is the actual issue ?
Is the scan failing ?
Can you please send the logs of your Github Action build ?

**Comment by melmols** [comment]
Issue is "Login failed" Error code 4. Here are the logs:

**[2020-04-22 08:58:56,565 INFO ] Verbose mode is activated. All messages and events will be sent to the console or log file.
[2020-04-22 08:58:56,585 INFO ] CxConsole version 8.90.2
[2020-04-22 08:58:56,585 INFO ] CxConsole scan session started
[2020-04-22 08:58:56,585 INFO ] 
[2020-04-22 08:58:56,589 INFO ] Default configuration file location: /home/runner/work/***/***/cxcli/config/cx_console.properties
[2020-04-22 08:58:57,506 INFO ] Command line parameters were checked successfully
[2020-04-22 08:58:57,576 INFO ] Default log file location: /home/runner/work/***/***/cxcli/logs/cx_console.log
[2020-04-22 08:58:59,098 INFO ] Trying to reach Checkmarx server, response code: 200
[2020-04-22 08:58:59,099 INFO ] Server connectivity test succeeded to: ***
[2020-04-22 08:58:59,519 ERROR] Failed to login with token: User authentication failed
[2020-04-22 08:58:59,521 INFO ] Project name is ***
[2020-04-22 08:58:59,522 INFO ] Logging into Checkmarx server.
[2020-04-22 08:58:59,534 INFO ]  Attempt #1 - Error occurred during Login
[2020-04-22 08:58:59,534 INFO ] Logging into Checkmarx server.
[2020-04-22 08:58:59,535 INFO ]  Attempt #2 - Error occurred during Login
[2020-04-22 08:58:59,535 INFO ] Logging into Checkmarx server.
[2020-04-22 08:58:59,538 INFO ]  Attempt #3 - Error occurred during Login
[2020-04-22 08:58:59,538 INFO ] Logging into Checkmarx server.
[2020-04-22 08:58:59,538 ERROR] Error executing SAST scan command: com.checkmarx.cxconsole.commands.job.exceptions.CLIJobException: Unsuccessful login.
[2020-04-22 08:58:59,539 INFO ] CxConsole session finished
[2020-04-22 08:58:59,539 ERROR] Failure - Login Failed - error code 4
##[error]Failed to execute command : The process '/home/runner/work/***/***/cxcli/runCxConsole.sh' failed with exit code 4**

**Comment by melmols** [comment]
Issue seems to be prominent in spinning scans with already existing projects. If It's a generated project being added, it works fine.

**Comment by miguelfreitas93** [comment]
can you please send me the CLI command that was running in the failed build ?
For example:
./cxcli/runCxConsole.sh Scan -CxServer *** -CxUser *** -CxPassword *** -ProjectName "***\TestProject-master" -preset "All" -LocationType folder -LocationPath "/home/runner/work/TestProject/TestProject" -Configuration "Default Configuration" -LocationPathExclude "tests,.vscode,.github,images,__pycache__,.pytest_cache,cxcli" -LocationFilesExclude "*.md,*.json,.gitignore,LICENSE" -SASTHigh 0 -SASTMedium 0 -Comment "git master@6e222abf2558373ac65610949a4d66b1616fa471" -Log "/home/runner/work/TestProject/TestProject/log.log" -v

**Comment by melmols** [comment]
Hi, yes of course!

name: Checkmarx SAST Scan
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Checkmarx Action
      uses: miguelfreitas93/checkmarx-github-action@v1.0.0
      with:
        cxServer: ${{ secrets.CX_SERVER }} 
        cxToken: ${{ secrets.CX_TOKEN }}
        cxTeam: ${{ secrets.CX_TEAM }} 
        cxIncremental: true
        cxPreset: "Same as in the server"
        cxConfiguration: "Same as in the server"
      id: cx_scan
    -  name: Echo output
       run: echo "Scan data:${{ steps.cx_scan.outputs }}"

**Comment by melmols** [comment]
Note: cxPreset and cxConfig match the values in the server configured for that project.

**Comment by miguelfreitas93** [comment]
please provide the CLI command that was running in the failed build, like I requested in the previous post

**Comment by melmols** [comment]
./cxcli/runCxConsole.sh Scan -CxServer *** -CxToken *** -ProjectName "***\???-CX-SAST" -preset "ASA-SDLC" -LocationType folder -LocationPath "/home/runner/work/???/???" -Configuration "Multi-language Scan" -LocationPathExclude "cxcli,test,tests,mock,mocks,spec,unit,debug,e2e,androidTest,build,dist,deploy,venv,maven,gradle,target,example,examples,samples,bin,gen,out,docs,proguard,lint,images,swagger,coverage,generated,.vs,.idea,.temp,.tmp,.grunt,.cache,.dynamodb,.fusebox,.serverless,.nyc_output,.git,.github,.dependabot,.semaphore,.circleci,.vscode,.nuget,.mvn,.m2,.DS_Store,.sass-cache,.gradle,__pycache__,.pytest_cache,.settings,res/color*,res/drawable*,res/mipmap*,res/anim*,*imageset,xcuserdata,xcshareddata,*xcassets,*appiconset,*xcodeproj,*framework,*lproj,__MACOSX,css,react,yui,node_modules,jquery*,angular*,bootstrap*,modernizr*,bower_components,jspm_packages,typings,dojo,package,packages,vendor,xjs" -Incremental -Comment "git CX-SAST@514b16e599e26c944e7e1bd9fa699eb541aa33ce" -v

**Comment by miguelfreitas93** [comment]
from where did you generate the token ?

**Comment by melmols** [comment]
Locally. Tested it with a circle ci build and locally. how come?

**Comment by miguelfreitas93** [comment]
What is the Version and HF of your Checkmarx Server ?

**Comment by miguelfreitas93** [comment]
I'm not able to replicate locally this behavior, as you can see below:
By any change you added an additional space or character to the CX_TOKEN in Secrets of Github?

runCxConsole.cmd Scan -CxServer ***** -CxToken **** -ProjectName "****\TestProject-NewProject" -LocationType folder -LocationPath "D:\Github\TestProject" -Log log.log -v -preset "All" -Configuration "Multi-language Scan" -Incremental
[2020-04-22 14:45:53,547 INFO ] Verbose mode is activated. All messages and events will be sent to the console or log file.
[2020-04-22 14:45:53,547 INFO ] CxConsole version 8.90.2
[2020-04-22 14:45:53,547 INFO ] CxConsole scan session started
[2020-04-22 14:45:53,554 INFO ]
[2020-04-22 14:45:53,557 INFO ] Default configuration file location: D:\CxConsolePlugin-8.90.2\config\cx_console.properties
[2020-04-22 14:45:54,335 INFO ] Command line parameters were checked successfully
[2020-04-22 14:45:54,337 INFO ] Log file location: D:\CxConsolePlugin-8.90.2\log.log
[2020-04-22 14:45:56,222 INFO ] Trying to reach Checkmarx server, response code: 200
[2020-04-22 14:45:56,226 INFO ] Server connectivity test succeeded to: *****
[2020-04-22 14:45:56,799 INFO ] Project name is TestProject-NewProject
[2020-04-22 14:45:56,799 INFO ] Logging into Checkmarx server.
[2020-04-22 14:45:56,801 INFO ] Login was completed successfully

**Comment by melmols** [comment]
Hi @miguelfreitas93 
Is there a way to remove the functionality of adding branch name to the name of the project?

As stated here: 
**Project name will be always the name of the Repository concatenated with branch scanned. For example: "TestRepository-master**"

Cheers

**Comment by miguelfreitas93** [comment]
If the project does not exist on Checkmarx Server, a new project should be created there.
It is best practice to have branch name in project name, when scanning from build servers.
Is the token that you're using valid ? usually those tokens have a time-to-live.
I was able to replicate on this scenario: 
https://github.com/miguelfreitas93/checkmarx-github-action/runs/625518439?check_suite_focus=true

**Comment by miguelfreitas93** [comment]
@melmols after investigated this issue https://github.com/miguelfreitas93/checkmarx-github-action/runs/625518439?check_suite_focus=true

I have concluded my token has expired. After retrieving a new token, I was able to authenticate again.
Please let me know if that fixed the issue

**Comment by miguelfreitas93** [comment]
I also added the possibility of override Project Name.
There is a new input available: cxProject
By default it will be: {{GITHUB_REPO_NAME}}-{{GITHUB_REPO_BRANCH}}

**Comment by melmols** [comment]
Hi @miguelfreitas93,

I was able to create new projects with that same token so looks good on that side. I didnt know they expired, i thought you had to revoke them for that. What the expiry range?
 And thank you very much. Really appreciate it.

Mel

**Comment by miguelfreitas93** [comment]
@melmols be aware we transferred this repo to another location.

you might need to change the location of the action to point to this place:
From:
uses: miguelfreitas93/checkmarx-github-action@v1.0.0
To:
uses: checkmarx-ts/checkmarx-github-action@v1.0.0

**Comment by melmols** [comment]
Hi Miguel, thanks for that. It has been changed. It seems to be ignoring the cxProject flag after I specify it. The project name is still changing per branch

**Comment by miguelfreitas93** [comment]
@melmols there was a problem with previous deploy. 
I just redeployed again with same version and it seems to work fine.
Can you please retry your github action build ?

**Comment by melmols** [comment]
Hi @miguelfreitas93

It is still not picking up the cxProject flag and appending the branch name.

**Comment by miguelfreitas93** [comment]
@melmols here a test:
https://github.com/checkmarx-ts/checkmarx-github-action/runs/673882317?check_suite_focus=true

Note these lines:
39 cxProject: **checkmarx-github-action**
94 ./cxcli/runCxConsole.sh Scan -CxServer *** -CxUser *** -CxPassword *** -ProjectName **"***\checkmarx-github-action"**
105 [2020-05-14 09:10:38,036 INFO ] Project name is checkmarx-github-action
111 [2020-05-14 09:10:38,681 INFO ] Project id for project: "checkmarx-github-action" was not found in server

**Comment by melmols** [comment]
Hi. Yes you mentioned before about the project being moved and I confirmed I did. I just did a re-test and it's now picking it up. Thank you
