### ISSUE TITLE
OSA report cannot be parsed to create issue

### ISSUE THREAD

**Issue by GregoireW** [checkmarx-ts/checkmarx-github-action#226]
If I execute an OSA scan and ask for issue creation, this is failing.

This is because the file is created as `report/CxOSASummary.json`, `report/CxOSALibraries.json` and `report/CxOSAVulnerabilities.json` but the osareport code try to open the file without the `.json` suffix :

https://github.com/checkmarx-ts/checkmarx-github-action/blob/ac69eb4ae89915313b403894f4e983676934471e/src/report/osareport.js#L7

https://github.com/checkmarx-ts/checkmarx-github-action/blob/ac69eb4ae89915313b403894f4e983676934471e/src/report/osareport.js#L40

(and the same for the 2 other files)

**Comment by miguelfreitas93** [comment]
@GregoireW please try:
uses: checkmarx-ts/checkmarx-github-action@master

and let me know if that works

**Comment by GregoireW** [comment]
@miguelfreitas93 This is now fixed. Thank you   (Note: I had a parameter cxOsaJson but I had to remove it for this to work)
