### ISSUE TITLE
Filter issue to create on github

### ISSUE THREAD

**Issue by GregoireW** [checkmarx-ts/checkmarx-github-action#228]
Hello,

When I scan my project I got a lot of issue created.  I would like to be able to create issue only it is major or medium and not minor. 
(create issue if issue level is greater than minor ) 

Is there a way to do this?

Thank you

**Comment by miguelfreitas93** [comment]
@GregoireW that is already implemented using CxFlow action in here https://github.com/checkmarx-ts/checkmarx-cxflow-github-action

**Comment by GregoireW** [comment]
Ah! 

Perhaps you should set a notice on this action (and on the cxflow action) to specify which one is to use primarily. 

It seems the cxFlow one should be preferred if you do not use OSA. (bad luck for me)

**Comment by miguelfreitas93** [comment]
@GregoireW exactly, cxflow action should be the prefered one. 
In case you have OSA, you can specify 2 different steps:
- 1 for SAST scan - using cxflow action - usually before dependencies resolution
- 1 for OSA scan - using cli action - usually after dependencies resolution
