### ISSUE TITLE
Do you have plan to set the MS Teams channel build notification integration

### ISSUE THREAD

**Issue by diptilenka** [checkmarx-ts/checkmarx-github-action#245]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![image-2021-08-11-22-32-44-404](https://user-images.githubusercontent.com/63293480/129844624-c95612ef-fe98-4d07-888d-6c0e1dc93342.png)

**Comment by miguelfreitas93** [comment]
@diptilenka this action is currently deprecated as you can see in the top of Readme, so there are no plans to implement new features. Please migrate to https://github.com/checkmarx-ts/checkmarx-cxflow-github-action and raise your feature request in that repository
