### ISSUE TITLE
If cxcli folder exists, unzip will fail and terminate process

### ISSUE THREAD

**Issue by matt-horner-by** [checkmarx-ts/checkmarx-github-action#3]
I am testing with nektos/act with the --reuse flag.  The flag leaves behind some of the artifacts from the previous runs.  In my case, with trying to test multiple times to ensure I have the action configured correctly, I have to remove the folders manually.

Can the existence of the folder be enough to short circuit the download/unzip process to enable rapid testing?  Would this have any side effects on the production version of GitHub workflows?

**Comment by miguelfreitas93** [comment]
@matt-horner-by can you please try to use version v1.0.1 and see if the problem was fixed ?

**Comment by miguelfreitas93** [comment]
Folder existence is being validated in the latest version.
closing the issue due to unresponsiveness from user
